In [1]:
import numpy as np
import pandas as pd
import geopandas as gpd
import intake

In [3]:
catalog = intake.open_catalog("../catalogs/*.yml")

bucket_name = 'city-planning-entitlements'

In [4]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [5]:
pcts_tables = ['tAPEL_CASE',
 'tAPLC',
 'tCASE',
 'tCOMMENT',
 'tCPC_CASE',
 'tDWELLING_UNITS',
 'tDWELLING_UNIT_SPECIALGROUPS',
 'tENV_CASE',
 'tHOLD_CASE',
 'tLA_PROP',
 'tLOC',
 'tPROP_CPIO',
 'tPROP_CUGU',
 'tPROP_GEO_INFO',
 'tPROP_SPECPLAN',
 'tZONING_CASE',
 'trefDWELLING_UNIT_PROPTYPE',
 'trefDWELLING_UNIT_SPECIALGROUPS',
 'trefHOLD_STG']

for table in pcts_tables:
    df = catalog.pcts[table].read()
    display(table)
    display(df.columns)
    display(df.head())

'tAPEL_CASE'

Index(['CASE_ID', 'BZA_APEL_END_DT', 'CC_APEL_FLG', 'ZA_SUPP_RPT_BZA_DT',
       'ADJ_OWNR_NOTIF_DT', 'BZA_ACTN_TXT', 'BZA_RPT_SIGN_DT',
       'BZA_APEL_CC_END_DT', 'BZA_APEL_SUBM_DT', 'BZA_NOTC_PUBL_DT',
       'BZA_PUBLC_HEAR_DT', 'BZA_DECISN_DT', 'APEL_EXT_FLG', 'APEL_EXT_TO_DT',
       'MYR_ACTN_DT', 'APEL_BDY_CD', 'CASE_NBR_CHG_LOG_ID', 'CPC_APEL_FLG',
       'APC_APEL_FLG', 'APC_AREA', 'APEL_ASSGN_STF_NM', 'APEL_ASSGN_STF_DT',
       'APEL_ASSGN_STF_PH', 'APEL_ASSGN_STF_COMMENT', 'COMM_PUBLC_HEAR_TM_TXT',
       'COMM_PUBLC_HEAR_LOC', 'COMM_CONTD_DT', 'COMM_ACTN', 'COMM_ACTN_DT',
       'COMM_ACTN_PRD_EXP_DT', 'COMM_ACTN_APEL_FLG', 'COMM_ACTN_TO_PLUM_DT',
       'APEL_EXPIR_DT', 'LOD_TO_CEA_DT'],
      dtype='object')

,CASE_ID,BZA_APEL_END_DT,CC_APEL_FLG,ZA_SUPP_RPT_BZA_DT,ADJ_OWNR_NOTIF_DT,BZA_ACTN_TXT,BZA_RPT_SIGN_DT,BZA_APEL_CC_END_DT,BZA_APEL_SUBM_DT,BZA_NOTC_PUBL_DT,BZA_PUBLC_HEAR_DT,BZA_DECISN_DT,APEL_EXT_FLG,APEL_EXT_TO_DT,MYR_ACTN_DT,APEL_BDY_CD,CASE_NBR_CHG_LOG_ID,CPC_APEL_FLG,APC_APEL_FLG,APC_AREA,APEL_ASSGN_STF_NM,APEL_ASSGN_STF_DT,APEL_ASSGN_STF_PH,APEL_ASSGN_STF_COMMENT,COMM_PUBLC_HEAR_TM_TXT,COMM_PUBLC_HEAR_LOC,COMM_CONTD_DT,COMM_ACTN,COMM_ACTN_DT,COMM_ACTN_PRD_EXP_DT,COMM_ACTN_APEL_FLG,COMM_ACTN_TO_PLUM_DT,APEL_EXPIR_DT,LOD_TO_CEA_DT
0,11042.0,1988-05-04,Y,NaT,1988-06-28,DENIED,1988-08-31,1988-09-15,NaT,1988-07-01,1988-07-26,NaT,N,NaT,NaT,None,0.0,None,None,None,None,NaT,None,None,None,None,NaT,None,NaT,NaT,None,NaT,NaT,NaT
1,11043.0,1988-05-04,Y,NaT,1988-06-28,DENIED,1988-08-31,1988-09-15,1988-09-22,1988-07-01,1988-07-26,NaT,N,NaT,NaT,None,0.0,None,None,None,None,NaT,None,None,None,None,NaT,None,NaT,NaT,None,NaT,NaT,NaT
2,11049.0,1988-08-21,N,NaT,1988-07-21,GRANTED,1988-09-23,NaT,NaT,NaT,1988-08-16,NaT,N,NaT,NaT,None,0.0,None,None,None,None,NaT,None,None,None,None,NaT,None,NaT,NaT,None,NaT,NaT,NaT
3,11050.0,1988-08-17,Y,NaT,1988-07-28,DENIED,1989-04-25,1989-05-10,NaT,1988-08-19,1988-09-13,NaT,N,NaT,NaT,None,0.0,None,None,None,None,NaT,None,None,None,None,NaT,None,NaT,NaT,None,NaT,NaT,NaT
4,11053.0,1988-07-10,N,NaT,1988-09-14,GRANTED,1988-10-27,NaT,NaT,NaT,1988-10-11,NaT,N,NaT,NaT,None,0.0,None,None,None,None,NaT,None,None,None,None,NaT,None,NaT,NaT,None,NaT,NaT,NaT

'tAPLC'

Index(['APLC_ID', 'APLC_TYP_CD', 'OWNR_APLC_FLG', 'REP_OWNR_FLG',
       'REP_APLC_FLG', 'APLC_RECV_DT', 'APLC_SENT_DT', 'APLC_CMPLT',
       'PLN_CHK_NBR', 'CNTR_ACTN_TXT', 'GEO_AREA_NBR', 'WNDW_FILE_PRD_NBR',
       'PROP_PRPSD_USGE_TXT', 'PROJ_DESC_TXT', 'SYS_USER_ID', 'TIMESTAMP',
       'APC_AREA_CD', 'PROJ_TOT_SQ_FT', 'PROJ_CMN_NM', 'CRTN_ID', 'CRTN_DT',
       'PRPSD_DESC_TXT', 'CNTCT_NM', 'CNTCT_PH', 'MAJOR_PROJ_FLG',
       'PRIVACY_OPTOUT_FLG'],
      dtype='object')

,APLC_ID,APLC_TYP_CD,OWNR_APLC_FLG,REP_OWNR_FLG,REP_APLC_FLG,APLC_RECV_DT,APLC_SENT_DT,APLC_CMPLT,PLN_CHK_NBR,CNTR_ACTN_TXT,GEO_AREA_NBR,WNDW_FILE_PRD_NBR,PROP_PRPSD_USGE_TXT,PROJ_DESC_TXT,SYS_USER_ID,TIMESTAMP,APC_AREA_CD,PROJ_TOT_SQ_FT,PROJ_CMN_NM,CRTN_ID,CRTN_DT,PRPSD_DESC_TXT,CNTCT_NM,CNTCT_PH,MAJOR_PROJ_FLG,PRIVACY_OPTOUT_FLG
0,10.0,ZA/CPC,None,None,None,1987-08-10,1987-08-26,1987-08-26,None,None,None,None,None,TO PERMIT OFF-SITE SALE OF BEER & WINE IN CONJ...,PAG_C19,1999-10-16,None,NaN,None,None,NaT,None,None,None,None,N
1,11.0,ZA/CPC,None,None,None,1987-07-24,1987-08-26,1987-08-26,None,None,None,None,None,THE CONTINUED USE AND MAINTENANCE OF AN EXISTI...,PAG_C19,1999-10-16,None,NaN,None,None,NaT,None,None,None,None,N
2,12.0,ZA/CPC,None,None,None,1987-08-05,1987-08-26,1987-08-26,None,None,None,None,None,TO PERMIT THE CONSTRUCTION AND MAINTENANCE OF ...,PAG_C19,1999-10-16,None,NaN,None,None,NaT,None,None,None,None,N
3,13.0,ZA/CPC,None,None,None,1987-08-26,1987-08-26,1987-08-26,None,None,None,None,None,THIS IS A BUILDING AND SAFETY APPEAL.,PAG_C19,1999-10-16,None,NaN,None,None,NaT,None,None,None,None,N
4,14.0,ZA/CPC,None,None,None,1987-08-11,1987-08-26,1987-08-26,None,None,None,None,None,TO PERMIT OFF-SITE SALE OF BEER AND WINE IN CO...,PAG_C19,1999-10-16,None,NaN,None,None,NaT,None,None,None,None,N

'tCASE'

Index(['CASE_ID', 'CASE_NBR', 'OLD_CASE_NBR', 'OLD_REQ_TYP_CD', 'CASE_STTS_CD',
       'APLC_ID', 'PLAN_OFC_ID', 'CASE_TYP_CD', 'CASE_FILE_RCV_DT',
       'CASE_FILE_SENT_DT', 'STRG_LOC_CD', 'CASE_FILE_WHO_TXT',
       'CASE_FILE_WHO_TEL_AREA_CD', 'CASE_FILE_WHO_TEL_NBR',
       'CASE_FILE_LOC_TXT', 'STRG_LOC_BOX_NBR', 'CASE_DEEM_CMPLT_DT',
       'EAF_NBR', 'CC_FILE_NBR', 'CC_HEAR_DT', 'CC_ACTN_TXT', 'PLUM_HEAR_DT',
       'PLUM_ACTN_TXT', 'APEL_BY_TXT', 'CNCL_DIST1_NBR', 'CNCL_DIST2_NBR',
       'CNCL_DIST3_NBR', 'CNCL_DIST4_NBR', 'RELCASE1_NBR', 'RELCASE2_NBR',
       'RELCASE3_NBR', 'RELCASE4_NBR', 'RELCASE5_NBR', 'RELCASE6_NBR',
       'GEN_CMT_TXT', 'SYS_USER_ID', 'TIMESTAMP', 'CRTN_ID', 'CRTN_DT',
       'CASE_YR_NBR', 'CASE_SEQ_NBR', 'PARNT_CASE_ID', 'PARNT_APEL_CNTR_NBR',
       'PARNT_APEL2_CNTR_NBR', 'PARNT_PA_CNTR_NBR', 'CASE_PROCS_CD',
       'ENVIRON_CLRNC_NBR', 'ENVIRON_CLRNC_DT', 'CASE_NBR_CHG_FLG',
       'PLAN_APPRV_DESC', 'PARNT_MODF_CNTR_NBR', 'LAST_DAY_TO_ACT',
       'MONITOR_COND_FLG', 'EXPEDITED_CASE_FLG', 'CASE_ACTION_ID',
       'TRACT_CASE_FLG', 'CP_RVW_DT', 'TERM_GRNT_EXPIR_DT',
       'COST_RECOVERY_FLG', 'MONITOR_STF_ASGN_ID', 'CC_ADOPTION_DT',
       'CC_CONTINUE_DT', 'CC_CONTINUE_BY', 'PLUM_CONTINUE_DT',
       'PARNT_RECONSIDR_CNTR_NBR', 'PARNT_CLRNC_CNTR_NBR',
       'CASE_FILE_WHO_EMAIL', 'ORD_STAT', 'CASE_TRANSFER_DT',
       'EIR_SUP_CNTR_NBR', 'EIR_ADD_CNTR_NBR', 'GEO_NBR',
       'EXPEDITED_FEE_CLRNC_DT', 'BOE_REF_NBR',
       'CASE_FILE_RCV_FROM_COUNTER_DT', 'EDITS_CASE_NBR', 'SIGN_OFF_NOTES',
       'MYPCTS_LIST_FLG', 'PROCESSING_UNIT', 'ORIGINAL_CASE_NBR',
       'PLAN_APPRV_TO_LIST', 'MAP_REQUESTED_DT', 'MAP_COMPLETED_DT',
       'DWELLINGUNITREASONID', 'PROCESSING_UNIT_CODE', 'DISCRETNARY_FLG',
       'ADM_ACTION_DT', 'ADM_ACTION_BY', 'LAST_DAYAPPEAL_DT',
       'LASTDAYTOFILEENTITLEMENT'],
      dtype='object')

,CASE_ID,CASE_NBR,OLD_CASE_NBR,OLD_REQ_TYP_CD,CASE_STTS_CD,APLC_ID,PLAN_OFC_ID,CASE_TYP_CD,CASE_FILE_RCV_DT,CASE_FILE_SENT_DT,STRG_LOC_CD,CASE_FILE_WHO_TXT,CASE_FILE_WHO_TEL_AREA_CD,CASE_FILE_WHO_TEL_NBR,CASE_FILE_LOC_TXT,STRG_LOC_BOX_NBR,CASE_DEEM_CMPLT_DT,EAF_NBR,CC_FILE_NBR,CC_HEAR_DT,CC_ACTN_TXT,PLUM_HEAR_DT,PLUM_ACTN_TXT,APEL_BY_TXT,CNCL_DIST1_NBR,CNCL_DIST2_NBR,CNCL_DIST3_NBR,CNCL_DIST4_NBR,RELCASE1_NBR,RELCASE2_NBR,RELCASE3_NBR,RELCASE4_NBR,RELCASE5_NBR,RELCASE6_NBR,GEN_CMT_TXT,SYS_USER_ID,TIMESTAMP,CRTN_ID,CRTN_DT,CASE_YR_NBR,CASE_SEQ_NBR,PARNT_CASE_ID,PARNT_APEL_CNTR_NBR,PARNT_APEL2_CNTR_NBR,PARNT_PA_CNTR_NBR,CASE_PROCS_CD,ENVIRON_CLRNC_NBR,ENVIRON_CLRNC_DT,CASE_NBR_CHG_FLG,PLAN_APPRV_DESC,PARNT_MODF_CNTR_NBR,LAST_DAY_TO_ACT,MONITOR_COND_FLG,EXPEDITED_CASE_FLG,CASE_ACTION_ID,TRACT_CASE_FLG,CP_RVW_DT,TERM_GRNT_EXPIR_DT,COST_RECOVERY_FLG,MONITOR_STF_ASGN_ID,CC_ADOPTION_DT,CC_CONTINUE_DT,CC_CONTINUE_BY,PLUM_CONTINUE_DT,PARNT_RECONSIDR_CNTR_NBR,PARNT_CLRNC_CNTR_NBR,CASE_FILE_WHO_EMAIL,ORD_STAT,CASE_TRANSFER_DT,EIR_SUP_CNTR_NBR,EIR_ADD_CNTR_NBR,GEO_NBR,EXPEDITED_FEE_CLRNC_DT,BOE_REF_NBR,CASE_FILE_RCV_FROM_COUNTER_DT,EDITS_CASE_NBR,SIGN_OFF_NOTES,MYPCTS_LIST_FLG,PROCESSING_UNIT,ORIGINAL_CASE_NBR,PLAN_APPRV_TO_LIST,MAP_REQUESTED_DT,MAP_COMPLETED_DT,DWELLINGUNITREASONID,PROCESSING_UNIT_CODE,DISCRETNARY_FLG,ADM_ACTION_DT,ADM_ACTION_BY,LAST_DAYAPPEAL_DT,LASTDAYTOFILEENTITLEMENT
0,66.0,PC-1987-764-PC,PC-87-0764,PC,None,66.0,None,PC,NaT,NaT,None,PUBLIC COUNTER,None,None,RM. 460-S,None,NaT,None,None,NaT,None,NaT,None,None,4,None,None,None,None,None,None,None,None,None,NOT APPEALED\,PAG_M026,2000-05-11 08:44:45,TG_C4,1999-10-16 00:00:00,1987.0,764.0,NaN,NaN,NaN,NaN,None,None,NaT,None,None,NaN,NaT,None,None,NaN,None,NaT,NaT,None,None,NaT,NaT,None,NaT,NaN,NaN,None,None,NaT,0.0,0.0,0.0,NaT,NaN,NaT,None,None,Y,None,None,None,NaT,NaT,0.0,None,None,NaT,None,NaT,NaT
1,67.0,PC-1987-761-PC,PC-87-0761,PC,None,67.0,None,PC,NaT,NaT,None,PUBLIC COUNTER,None,None,RM. 460-S,None,NaT,None,None,NaT,None,NaT,None,None,15,None,None,None,None,None,None,None,None,None,NOT APPEALED\,PAG_M026,2000-05-11 08:44:45,TG_C4,1999-10-16 00:00:00,1987.0,761.0,NaN,NaN,NaN,NaN,None,None,NaT,None,None,NaN,NaT,None,None,NaN,None,NaT,NaT,None,None,NaT,NaT,None,NaT,NaN,NaN,None,None,NaT,0.0,0.0,0.0,NaT,NaN,NaT,None,None,Y,None,None,None,NaT,NaT,0.0,None,None,NaT,None,NaT,NaT
2,68.0,CPC-1987-640-ZC,CPC-87-640,ZC,None,68.0,None,CPC,NaT,NaT,SG,RECORDS CENTER,213,4738440,PIPER TECH,None,1987-09-02,None,CF-88-0032,1988-03-08,None,NaT,None,None,2,None,None,None,None,None,None,None,None,None,None,PAG_M026,2000-05-11 08:46:01,PAG_C15,1999-10-16 20:19:11,1987.0,640.0,NaN,NaN,NaN,NaN,C,None,NaT,None,None,NaN,NaT,None,None,NaN,None,NaT,NaT,None,None,NaT,NaT,None,NaT,NaN,NaN,None,None,NaT,0.0,0.0,0.0,NaT,NaN,NaT,None,None,N,None,None,None,NaT,NaT,0.0,None,None,NaT,None,NaT,NaT
3,70.0,PC-1987-758-PC,PC-87-0758,PC,None,70.0,None,PC,NaT,NaT,None,PUBLIC COUNTER,None,None,RM. 460-S,None,NaT,None,None,NaT,None,NaT,None,None,9,None,None,None,None,None,None,None,None,None,NOT APPEALED\,PAG_M026,2000-05-11 08:44:45,TG_C4,1999-10-16 00:00:00,1987.0,758.0,NaN,NaN,NaN,NaN,None,None,NaT,None,None,NaN,NaT,None,None,NaN,None,NaT,NaT,None,None,NaT,NaT,None,NaT,NaN,NaN,None,None,NaT,0.0,0.0,0.0,NaT,NaN,NaT,None,None,Y,None,None,None,NaT,NaT,0.0,None,None,NaT,None,NaT,NaT
4,72.0,CPC-1987-630-BL,CPC-87-630,BL,None,72.0,None,CPC,NaT,NaT,SG,RECORDS CENTER,213,4738440,PIPER TECH,None,1987-09-02,None,CF-87-2053,NaT,None,NaT,None,None,7,None,None,None,CPC-87-629-ZC,None,None,None,None,None,9-2-87 APP FILED\10-5-87 PUB HEAR 11:00 AM IN ...,PAG_M026,2000-05-11 08:46:01,PAG_C15,1999-10-16 20:19:11,1987.0,630.0,NaN,NaN,NaN,NaN,C,None,NaT,None,None,NaN,NaT,None,None,NaN,None,NaT,NaT,None,None,NaT,NaT,None,NaT,NaN,NaN,None,None,NaT,0.0,0.0,0.0,NaT,NaN,NaT,None,None,N,None,None,None,NaT,NaT,0.0,None,None,NaT,None,NaT,NaT

'tCOMMENT'

Index(['COMMENT_ID', 'CASE_ID', 'COMMENT_DT', 'COMMENT_TXT', 'SYS_USER_ID',
       'COMMENT_TYP'],
      dtype='object')

,COMMENT_ID,CASE_ID,COMMENT_DT,COMMENT_TXT,SYS_USER_ID,COMMENT_TYP
0,93.0,107334.0,NaT,04/22/03- CONDITION # 25 GENERALIZED LANDSCAPI...,None,C
1,24910.0,149785.0,2006-05-16 14:08:57,CASE DISTRIBUTED.,87505,C
2,24911.0,146117.0,2006-05-16 14:31:33,SR MAILED & DISTRIBUTED.,87505,C
3,24912.0,101150.0,NaT,NO APPEAL,None,C
4,11.0,127594.0,NaT,3/16/04-CASE DISTRIBUTED (JH),None,C

'tCPC_CASE'

Index(['CASE_ID', 'CPC_INIT_PPR_DT', 'HEAR_DT', 'HEAR_TM_TXT', 'HEAR_LOC_TXT',
       'HEAR_NOTC_MEDIA_DT', 'HEAR_NOTC_PUBL_DT', 'HEAR_EXAM_RPT_DUE_DT',
       'ADDL_PROP_LOC_TXT', 'CPC_RECONSDR_FLG', 'ADDL_PROP_EXIST_ZONE_TXT',
       'ADDL_PROP_PRPSD_ZONE_TXT', 'ADDL_PROP_EXIST_GP_TXT',
       'ADDL_PROP_PRPSD_GP_TXT', 'ORDN_NBR', 'ORDN_ADPT_DT', 'ORDN_PUBL_DT',
       'ORDN_EFF_DT', 'CPC_DTRM_DT', 'CPC_MTG_LOC_TXT', 'CPC_ACTN_TXT',
       'CPC_ACTN_SENT_CC_DT', 'CPC_ACTN_ADVSD_DT', 'CPC_ACTN_LST_APEL_DT',
       'CASE_RCV_DRAFTG_DT', 'GPAB_ACTN_TXT', 'GPAB_DTRM_DT',
       'ZBA_TENTV_ACTN_FLG', 'ZBA_TENTV_ACTN_DT', 'ZBA_TENTV_ACTN_APEL_DT',
       'Q_PARENTH_RMVL_DT', 'T_RMVL_DT', 'Q_ORDN_TERMIN_DT',
       'APEL_TIME_EXT_RCV_DT', 'APEL_TIME_EXT_DT', 'ERC_DTRM_DT',
       'HEAR_OFCR_NM', 'RESP_PLNR1_NM', 'RESP_PLNR2_NM', 'WNDW_FILE_PRD_TXT',
       'GEO_CASE_NBR', 'WNDW_ITEM_NBR_TXT', 'FEES_PD_DT', 'STAFF_RECOM_TXT',
       'CASE_NBR_CHG_LOG_ID', 'CASE_FILE_RCV_DT', 'STF_ASGN_DT', 'ASGN_STF_NM',
       'ASGN_STF_TEL_AREA_CD', 'ASGN_STF_TEL_NBR', 'APC_MTG_DT',
       'CPC_CONTNU_DT', 'CONTINUED_BY', 'CONTNU_STF_TEL_AREA_CD',
       'CONTNU_STF_TEL_NBR', 'BATCH_WNDW_NBR', 'APEL_PRD_END_DT',
       'HEAR_WAIVED_FLG', 'DT_HEAR_WAIVED', 'COMMISSION_WAIVED_DT',
       'COMMISSION_WAIVED_FLG', 'HEAR_OFCR_ASGN_DT', 'LOD_TO_CEA_DT'],
      dtype='object')

,CASE_ID,CPC_INIT_PPR_DT,HEAR_DT,HEAR_TM_TXT,HEAR_LOC_TXT,HEAR_NOTC_MEDIA_DT,HEAR_NOTC_PUBL_DT,HEAR_EXAM_RPT_DUE_DT,ADDL_PROP_LOC_TXT,CPC_RECONSDR_FLG,ADDL_PROP_EXIST_ZONE_TXT,ADDL_PROP_PRPSD_ZONE_TXT,ADDL_PROP_EXIST_GP_TXT,ADDL_PROP_PRPSD_GP_TXT,ORDN_NBR,ORDN_ADPT_DT,ORDN_PUBL_DT,ORDN_EFF_DT,CPC_DTRM_DT,CPC_MTG_LOC_TXT,CPC_ACTN_TXT,CPC_ACTN_SENT_CC_DT,CPC_ACTN_ADVSD_DT,CPC_ACTN_LST_APEL_DT,CASE_RCV_DRAFTG_DT,GPAB_ACTN_TXT,GPAB_DTRM_DT,ZBA_TENTV_ACTN_FLG,ZBA_TENTV_ACTN_DT,ZBA_TENTV_ACTN_APEL_DT,Q_PARENTH_RMVL_DT,T_RMVL_DT,Q_ORDN_TERMIN_DT,APEL_TIME_EXT_RCV_DT,APEL_TIME_EXT_DT,ERC_DTRM_DT,HEAR_OFCR_NM,RESP_PLNR1_NM,RESP_PLNR2_NM,WNDW_FILE_PRD_TXT,GEO_CASE_NBR,WNDW_ITEM_NBR_TXT,FEES_PD_DT,STAFF_RECOM_TXT,CASE_NBR_CHG_LOG_ID,CASE_FILE_RCV_DT,STF_ASGN_DT,ASGN_STF_NM,ASGN_STF_TEL_AREA_CD,ASGN_STF_TEL_NBR,APC_MTG_DT,CPC_CONTNU_DT,CONTINUED_BY,CONTNU_STF_TEL_AREA_CD,CONTNU_STF_TEL_NBR,BATCH_WNDW_NBR,APEL_PRD_END_DT,HEAR_WAIVED_FLG,DT_HEAR_WAIVED,COMMISSION_WAIVED_DT,COMMISSION_WAIVED_FLG,HEAR_OFCR_ASGN_DT,LOD_TO_CEA_DT
0,6.0,NaT,1987-09-28,9:30 AM,561-A-CH,1987-09-01,1987-09-04,1987-10-19,None,None,None,None,None,None,None,NaT,NaT,NaT,1987-11-05,None,DISAPP,1987-11-10,1987-11-10,NaT,1987-08-26,None,NaT,None,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,LYOU,None,None,None,None,None,NaT,None,0.0,NaT,NaT,None,None,None,NaT,NaT,None,None,None,None,NaT,None,NaT,NaT,None,NaT,NaT
1,521.0,NaT,1987-08-17,9:30 AM,CITY HALL,NaT,NaT,NaT,None,None,None,None,None,None,None,NaT,NaT,NaT,1987-10-08,None,APPROV,1987-10-16,1987-10-16,NaT,NaT,None,NaT,None,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,PAUL BEARD,None,None,None,None,None,NaT,None,0.0,NaT,NaT,None,None,None,NaT,NaT,None,None,None,None,NaT,None,NaT,NaT,None,NaT,NaT
2,522.0,NaT,1987-08-24,9:30 AM,CITY HALL,NaT,NaT,NaT,None,None,None,None,None,None,"166,564",1991-01-11,1991-01-17,NaT,1987-10-22,None,APPROV,1987-11-04,1987-11-04,NaT,NaT,None,NaT,None,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,None,None,None,None,None,None,NaT,None,0.0,NaT,NaT,None,None,None,NaT,NaT,None,None,None,None,NaT,None,NaT,NaT,None,NaT,NaT
3,523.0,NaT,1987-08-17,9:30 AM,CITY HALL,NaT,NaT,NaT,None,None,None,None,None,None,None,NaT,NaT,NaT,1987-10-16,None,COMMIS,1987-10-28,1987-10-28,NaT,NaT,None,NaT,None,NaT,NaT,NaT,NaT,NaT,1989-06-15,NaT,NaT,VON SCHOENBORN,None,None,None,None,None,NaT,None,0.0,NaT,NaT,None,None,None,NaT,NaT,None,None,None,None,NaT,None,NaT,NaT,None,NaT,NaT
4,524.0,NaT,1987-08-24,10:00 AM,W LOS ANGELES,1987-07-28,1987-07-31,1987-09-14,None,None,None,None,None,None,"163,324",1988-03-01,1988-03-07,NaT,1987-10-13,None,GRANTE,1987-10-21,1987-10-21,NaT,NaT,None,NaT,None,NaT,NaT,NaT,1989-02-02,NaT,1989-06-15,NaT,NaT,PAUL BEARD,None,None,None,None,None,NaT,None,0.0,NaT,NaT,None,None,None,NaT,NaT,None,None,None,None,NaT,None,NaT,NaT,None,NaT,NaT

'tDWELLING_UNITS'

Index(['ItemID', 'CaseID', 'CaseNumber', 'UnitTypeID', 'ProposedExisting',
       'ProposedToBeDemolished', 'ProposedAdding', 'ProposedTotal',
       'ApprovedExisting', 'ApprovedToBeDemolished', 'ApprovedAdding',
       'ApprovedTotal', 'SignedOffExisting', 'SignedOffToBeDemolished',
       'SignedOffAdding', 'SignedOffTotal', 'CreatedBy', 'CreatedOn',
       'LastModifiedBy', 'LastModifiedOn', 'IsSignedOff', 'PropCreatedBy',
       'PropCreatedOn', 'PropLastModifiedBy', 'PropLastModifiedOn',
       'ApprovedCreatedBy', 'ApprovedCreatedOn', 'ApprovedLastModifiedBy',
       'ApprovedLastModifiedOn', 'SignedOffCreatedBy', 'SignedOffCreatedOn',
       'SignedOffLastModifiedBy', 'SignedOffLastModifiedOn', 'CreatedById',
       'LastModifiedById', 'PropCreatedById', 'PropLastModifiedById',
       'ApprovedCreatedById', 'ApprovedLastModifiedById',
       'SignedOffCreatedById', 'SignedOffLastModifiedById', 'BaseUnits'],
      dtype='object')

,ItemID,CaseID,CaseNumber,UnitTypeID,ProposedExisting,ProposedToBeDemolished,ProposedAdding,ProposedTotal,ApprovedExisting,ApprovedToBeDemolished,ApprovedAdding,ApprovedTotal,SignedOffExisting,SignedOffToBeDemolished,SignedOffAdding,SignedOffTotal,CreatedBy,CreatedOn,LastModifiedBy,LastModifiedOn,IsSignedOff,PropCreatedBy,PropCreatedOn,PropLastModifiedBy,PropLastModifiedOn,ApprovedCreatedBy,ApprovedCreatedOn,ApprovedLastModifiedBy,ApprovedLastModifiedOn,SignedOffCreatedBy,SignedOffCreatedOn,SignedOffLastModifiedBy,SignedOffLastModifiedOn,CreatedById,LastModifiedById,PropCreatedById,PropLastModifiedById,ApprovedCreatedById,ApprovedLastModifiedById,SignedOffCreatedById,SignedOffLastModifiedById,BaseUnits
0,82,191139,ZA-2013-1085-CDP-MEL-ZAA,11,1,1,3,3,0,0,0,0,0,0,0,0,910.0,2015-11-02 08:10:30,874.0,2015-11-02 16:14:56,False,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,dcp\372350,dcp\296281,None,None,None,None,None,None,NaN
1,84,200483,ZA-2013-1085-CDP-MEL-ZAA-1A,11,1,1,3,3,1,1,2,2,0,1,2,1,910.0,2015-11-02 08:14:45,874.0,2015-11-02 14:04:59,True,NaN,NaT,NaN,NaT,NaN,2015-11-02 14:04:59,NaN,NaT,NaN,2015-11-02 14:04:59,NaN,NaT,dcp\372350,dcp\296281,None,None,None,None,None,None,NaN
2,85,199944,DIR-2014-4378-DB,12,0,0,27,27,0,0,27,27,0,0,0,0,868.0,2015-11-02 09:47:11,868.0,2015-11-09 11:46:28,False,NaN,NaT,NaN,NaT,NaN,2015-11-09 11:46:28,NaN,NaT,NaN,NaT,NaN,NaT,dcp\335242,dcp\335242,None,None,None,None,None,None,NaN
3,86,199944,DIR-2014-4378-DB,17,0,0,3,3,0,0,3,3,0,0,0,0,868.0,2015-11-02 09:47:42,868.0,2015-11-09 11:46:36,False,NaN,NaT,NaN,NaT,NaN,2015-11-09 11:46:36,NaN,NaT,NaN,NaT,NaN,NaT,dcp\335242,dcp\335242,None,None,None,None,None,None,NaN
4,87,199944,DIR-2014-4378-DB,3,7992,7992,0,0,0,7992,0,0,0,0,0,0,868.0,2015-11-02 09:50:39,868.0,2015-11-09 11:47:00,False,NaN,NaT,NaN,NaT,NaN,2015-11-09 11:47:00,NaN,NaT,NaN,NaT,NaN,NaT,dcp\335242,dcp\335242,None,None,None,None,None,None,NaN

'tDWELLING_UNIT_SPECIALGROUPS'

Index(['ItemID', 'SpecialGroupID'], dtype='object')

   ItemID  SpecialGroupID
0    4996               9
1    5019               9
2    5074               9
3    5075               9
4    5079               9

'tENV_CASE'

Index(['CASE_ID', 'DOT_DTRM_CD', 'DOT_CNTCT_NM', 'DOT_TEL_AREA_CD',
       'DOT_TEL_NBR', 'ESAC_RVW_CD', 'ESAC_RVW_DT', 'PUB_DT', 'PUB_END_DT',
       'CMT_RCV_CD', 'FRST_CMT_RCV_DT', 'CMT_RPLY_DT', 'ASGN_STF_NM',
       'STF_ASGN_DT', 'ASGN_STF_TEL_AREA_CD', 'ASGN_STF_TEL_NBR',
       'ENV_CASE_FILE_RCV_DT', 'NOTICE_OF_INTENT_TO_ADOPT_CD',
       'CASE_NBR_CHG_LOG_ID', 'TRAF_STUDY_REQ_FLG', 'DOT_DTRM_DT',
       'DOT_RVW_REQ_DT', 'DOT_DTRM_RECV_DT', 'DOT_CLRNC_RECV_DT',
       'FINAL_EIR_DISTR_DT', 'ENV_TERM', 'ENV_TERM_DT', 'RECONSIDR_LTR_SNT_DT',
       'EIR_NOP_START_DT', 'EIR_NOP_END_DT', 'SCOPING_MEETING_DT',
       'DEIR_CIRCULATION_START_DT', 'DEIR_CIRCULATION_END_DT', 'EIR_NOC_DT',
       'EIR_REQUIRED_DT', 'SCOPE_MEETING_REQUIRED_FLG', 'EIR_TERM_DT',
       'DEIR_PROJ_NM', 'DEIR_PROJ_DESC', 'DEIR_PROJ_STATUS', 'EXEMPTION_NBR',
       'LETTER_SENTTOTRIBES_DT'],
      dtype='object')

,CASE_ID,DOT_DTRM_CD,DOT_CNTCT_NM,DOT_TEL_AREA_CD,DOT_TEL_NBR,ESAC_RVW_CD,ESAC_RVW_DT,PUB_DT,PUB_END_DT,CMT_RCV_CD,FRST_CMT_RCV_DT,CMT_RPLY_DT,ASGN_STF_NM,STF_ASGN_DT,ASGN_STF_TEL_AREA_CD,ASGN_STF_TEL_NBR,ENV_CASE_FILE_RCV_DT,NOTICE_OF_INTENT_TO_ADOPT_CD,CASE_NBR_CHG_LOG_ID,TRAF_STUDY_REQ_FLG,DOT_DTRM_DT,DOT_RVW_REQ_DT,DOT_DTRM_RECV_DT,DOT_CLRNC_RECV_DT,FINAL_EIR_DISTR_DT,ENV_TERM,ENV_TERM_DT,RECONSIDR_LTR_SNT_DT,EIR_NOP_START_DT,EIR_NOP_END_DT,SCOPING_MEETING_DT,DEIR_CIRCULATION_START_DT,DEIR_CIRCULATION_END_DT,EIR_NOC_DT,EIR_REQUIRED_DT,SCOPE_MEETING_REQUIRED_FLG,EIR_TERM_DT,DEIR_PROJ_NM,DEIR_PROJ_DESC,DEIR_PROJ_STATUS,EXEMPTION_NBR,LETTER_SENTTOTRIBES_DT
0,102184.0,None,None,None,None,None,NaT,NaT,NaT,None,NaT,NaT,None,NaT,None,None,NaT,None,0.0,None,NaT,NaT,NaT,NaT,NaT,None,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,None,NaT,None,None,0.0,None,NaT
1,102186.0,None,None,None,None,None,NaT,NaT,NaT,None,NaT,NaT,None,NaT,None,None,NaT,None,0.0,None,NaT,NaT,NaT,NaT,NaT,None,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,None,NaT,None,None,0.0,None,NaT
2,102188.0,None,None,None,None,None,NaT,NaT,NaT,None,NaT,NaT,None,NaT,None,None,NaT,None,0.0,None,NaT,NaT,NaT,NaT,NaT,None,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,None,NaT,None,None,0.0,None,NaT
3,102190.0,None,None,None,None,None,NaT,NaT,NaT,None,NaT,NaT,None,NaT,None,None,NaT,None,0.0,None,NaT,NaT,NaT,NaT,NaT,None,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,None,NaT,None,None,0.0,None,NaT
4,102192.0,None,None,None,None,None,NaT,NaT,NaT,None,NaT,NaT,None,NaT,None,None,NaT,None,0.0,None,NaT,NaT,NaT,NaT,NaT,None,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,None,NaT,None,None,0.0,None,NaT

'tHOLD_CASE'

Index(['HOLD_ID', 'CASE_ID', 'HOLD_START_DT', 'HOLD_RSN_TXT', 'HOLD_END_DT',
       'SYS_USER_ID', 'TIMESTAMP', 'CRTN_ID', 'CRTN_DT', 'HOLD_STG_ID',
       'HOLD_CMT_TXT'],
      dtype='object')

,HOLD_ID,CASE_ID,HOLD_START_DT,HOLD_RSN_TXT,HOLD_END_DT,SYS_USER_ID,TIMESTAMP,CRTN_ID,CRTN_DT,HOLD_STG_ID,HOLD_CMT_TXT
0,296.0,128119.0,2004-04-14,1. UNCOVERED PARKING IS NOT ALLOWED IN THE RA...,2004-06-30,26224,2004-06-30 14:21:46,26224,2004-06-16 16:03:49,1.0,None
1,302.0,129806.0,2004-06-17,1. THE PLOT PLAN NEEDS TO BE REPLACED AND REV...,2004-07-08,26224,2004-07-08 15:54:49,26224,2004-06-17 14:45:59,1.0,None
2,20706.0,185890.0,2012-03-07,ADDITIONAL ENTITLEMENTS FOR PAVED FRONT YARD M...,2012-03-19,45563,2012-03-19 10:13:57,45563,2012-03-19 10:10:49,1.0,"3/9/12 - Mtg. w/Phillip Kaainoa, he will discu..."
3,20707.0,186018.0,2012-03-16,ALCOHOL QUESTIONS (FORMCP-7773) NOT ANSWERED. ...,2012-06-27,45563,2012-06-27 11:30:00,45563,2012-03-19 11:28:21,1.0,"6/27/12 - floor plans still sloppy, but at lea..."
4,20721.0,184506.0,2012-03-16,APPLICANT REQUESTED MORE TIME TO MEET WITH NEI...,2013-08-01,93775,2013-08-14 09:08:51,45541,2012-03-20 14:22:26,2.0,None

'tLA_PROP'

Index(['PROP_ID', 'PROP_TYP_CD', 'BOE_VLD_ADDR_FLG', 'PROP_CMN_NM',
       'ASSR_PRCL_NBR', 'MULTI_PRCL_FLG', 'TRACT_NBR', 'BLCK_NBR', 'LOT_NBR',
       'ARB_NBR', 'MULTI_LOT_FLG', 'STR_NBR', 'STR_NBR_RNG_END',
       'STR_FRAC_NBR', 'STR_FRAC_NBR_RNG_END', 'STR_DIR_CD', 'STR_NM',
       'OLD_STRNM_TXT', 'STR_SFX_CD', 'STR_SFX_DIR_CD', 'STR_UNIT_TYP_CD',
       'UNIT_NBR', 'UNIT_NBR_RNG_END', 'ZIP_CD', 'ZIP_CD_SFX', 'CNCL_DIST_NBR',
       'PLAN_AREA_NBR', 'ZONE_REG_CD', 'BOE_DIST_MAP_NBR', 'CENSUS_TRACT_NBR',
       'ZONE_MAP_NBR', 'PLAN_LAND_USE_TXT', 'PLAN_ZONE_TXT',
       'ENVIRON_CLRNC_NBR', 'ENVIRON_CLRNC_DT', 'LOT_AREA_SQ_FT_NBR',
       'LOT_DIM_TXT', 'TOT_PROJ_SQ_FT_NBR', 'PROP_RET_DT', 'PARNT_PROP_ID',
       'PROP_CURR_USGE_TXT', 'SYS_USER_ID', 'TIMESTAMP', 'PIN', 'APC_AREA_CD',
       'CNC_CD', 'CRTN_ID', 'CRTN_DT', 'HPOZ', 'COMM_CNCL_CD',
       'CRA_REDEV_PROJECTID'],
      dtype='object')

,PROP_ID,PROP_TYP_CD,BOE_VLD_ADDR_FLG,PROP_CMN_NM,ASSR_PRCL_NBR,MULTI_PRCL_FLG,TRACT_NBR,BLCK_NBR,LOT_NBR,ARB_NBR,MULTI_LOT_FLG,STR_NBR,STR_NBR_RNG_END,STR_FRAC_NBR,STR_FRAC_NBR_RNG_END,STR_DIR_CD,STR_NM,OLD_STRNM_TXT,STR_SFX_CD,STR_SFX_DIR_CD,STR_UNIT_TYP_CD,UNIT_NBR,UNIT_NBR_RNG_END,ZIP_CD,ZIP_CD_SFX,CNCL_DIST_NBR,PLAN_AREA_NBR,ZONE_REG_CD,BOE_DIST_MAP_NBR,CENSUS_TRACT_NBR,ZONE_MAP_NBR,PLAN_LAND_USE_TXT,PLAN_ZONE_TXT,ENVIRON_CLRNC_NBR,ENVIRON_CLRNC_DT,LOT_AREA_SQ_FT_NBR,LOT_DIM_TXT,TOT_PROJ_SQ_FT_NBR,PROP_RET_DT,PARNT_PROP_ID,PROP_CURR_USGE_TXT,SYS_USER_ID,TIMESTAMP,PIN,APC_AREA_CD,CNC_CD,CRTN_ID,CRTN_DT,HPOZ,COMM_CNCL_CD,CRA_REDEV_PROJECTID
0,16.0,None,None,None,6058008014,None,TR 7906,None,90,None,N,N/A,None,None,None,None,104TH,104TH ST,ST,None,None,None,None,None,None,8,105.0,R1-1,Multiple,2380.00,None,Low Residential,None,ND-86-229,NaT,None,None,None,NaT,NaN,None,TG_C5,1999-10-16 19:09:12,090A193 16,S,12.0,None,NaT,None,None,NaN
1,17.0,None,None,None,None,None,None,None,None,None,N,N/A,None,None,None,None,105TH,105TH ST,ST,None,None,None,None,None,None,None,NaN,None,None,None,None,None,None,None,NaT,None,None,None,NaT,NaN,None,TG_C5,1999-10-16 19:09:12,None,None,NaN,None,NaT,None,None,NaN
2,18.0,None,None,None,None,None,None,None,None,None,N,N/A,None,None,None,None,107TH,107TH ST,ST,None,None,None,None,None,None,None,NaN,None,None,None,None,None,None,None,NaT,None,None,None,NaT,NaN,None,TG_C5,1999-10-16 19:09:12,None,None,NaN,None,NaT,None,None,NaN
3,19.0,None,None,None,None,None,None,None,None,None,N,N/A,None,None,None,None,108TH,108TH ST,ST,None,None,None,None,None,None,None,NaN,None,None,None,None,None,None,None,NaT,None,None,None,NaT,NaN,None,TG_C5,1999-10-16 19:09:12,None,None,NaN,None,NaT,None,None,NaN
4,20.0,None,None,None,None,None,None,None,None,None,N,N/A,None,None,None,None,108TH,108TH STREET,ST,None,None,,None,None,None,None,NaN,None,None,None,None,None,None,None,NaT,None,None,None,NaT,NaN,None,PAV_M11,1999-11-16 14:20:49,None,None,NaN,None,NaT,None,None,NaN

'tLOC'

Index(['LOC_ID', 'APLC_ID', 'LOC_TYP_CD', 'LOC_PRIMARY_FLG'], dtype='object')

       LOC_ID  APLC_ID LOC_TYP_CD LOC_PRIMARY_FLG
0  58978841.0  21230.0          L               Y
1  58978842.0  21284.0          L               Y
2  58967874.0  32983.0          L               Y
3       636.0  41874.0          L               Y
4       636.0  44096.0          L               Y

'tPROP_CPIO'

Index(['PROP_ID', 'CPIO'], dtype='object')

      PROP_ID                                  CPIO
0  59049039.0                                Sylmar
1  59399526.0  West Adams - Baldwin Hills - Leimert
2  59045841.0                                Sylmar
3  59049041.0                                Sylmar
4  59045840.0                                Sylmar

'tPROP_CUGU'

Index(['PROP_ID', 'CUGU'], dtype='object')

      PROP_ID                CUGU
0  59380894.0       Boyle Heights
1  59428033.0  Pacoima/Sun Valley
2  59425452.0       Boyle Heights
3  59380901.0       Boyle Heights
4  59380910.0       Boyle Heights

'tPROP_GEO_INFO'

Index(['PROP_GEO_INFO_ID', 'PROP_ID', 'CASE_ID', 'PROP_GEO_INFO_TYP',
       'PROP_GEO_INFO_VAL', 'EFFECTIVE_DT', 'CNCL_DIST_NBR', 'TEMP_PIN',
       'CRTN_DT', 'CRTN_ID', 'TIMESTAMP', 'SYS_USER_ID'],
      dtype='object')

,PROP_GEO_INFO_ID,PROP_ID,CASE_ID,PROP_GEO_INFO_TYP,PROP_GEO_INFO_VAL,EFFECTIVE_DT,CNCL_DIST_NBR,TEMP_PIN,CRTN_DT,CRTN_ID,TIMESTAMP,SYS_USER_ID
0,350.0,34237.0,99538.0,CNCL_DIST_NBR,1,2002-08-20,1,135A209 39,2002-08-20,59527,2002-08-20,59527
1,351.0,34237.0,99539.0,CNCL_DIST_NBR,1,2000-12-04,1,135A209 39,2000-12-04,59527,2000-12-04,59527
2,352.0,34306.0,99666.0,CNCL_DIST_NBR,1,2001-05-14,1,130-5A201 171,2001-05-14,29592,2001-05-14,29592
3,353.0,34306.0,99667.0,CNCL_DIST_NBR,1,2000-12-12,1,130-5A201 171,2000-12-12,29592,2000-12-12,29592
4,354.0,34323.0,99722.0,CNCL_DIST_NBR,1,2001-05-18,1,135A213 210,2001-05-18,45375,2001-05-18,45375

'tPROP_SPECPLAN'

Index(['PROP_ID', 'SPECPLAN', 'SPECIFICPLANID'], dtype='object')

      PROP_ID                               SPECPLAN  SPECIFICPLANID
0  59391255.0  Ventura / Cahuenga Boulevard Corridor            23.0
1  59391265.0  Ventura / Cahuenga Boulevard Corridor            23.0
2  59391268.0  Ventura / Cahuenga Boulevard Corridor            23.0
3  59036193.0                          Warner Center            26.0
4  58987755.0        South Los Angeles Alcohol Sales            14.0

'tZONING_CASE'

Index(['CASE_ID', 'AZA_ASGN_DT', 'AZA_NM', 'ZI_ASGN_DT', 'ZI_NM', 'HEAR_DT',
       'HEAR_TM_TXT', 'HEAR_LOC_TXT', 'HEAR_NOTC_MEDIA_DT',
       'HEAR_NOTC_PUBL_DT', 'ZI_RPT_DUE_DT', 'ZI_DRAFT_RPT_DT',
       'ZI_RPT_CMPLT_DT', 'ZI_RPT_RCV_ZA_DT', 'ZA_ACTN_DT', 'ZA_ACTN_TXT',
       'APEL_PRD_END_DT', 'ZA_SUPP_RPT_DUE_DT', 'BZA_CASE_NBR',
       'ZA_APEL_SUBM_BZA_DT', 'ZA_ACTN_APEL_FLG', 'COND_ACTN_CLRNC_TXT',
       'CASE_NBR_CHG_LOG_ID', 'CASE_FILE_RCV_DT', 'STF_ASGN_DT', 'ASGN_STF_NM',
       'ASGN_STF_TEL_AREA_CD', 'ASGN_STF_TEL_NBR', 'RE_HEAR_NEEDED_FLG',
       'HEAR_WAIVED_FLG', 'DT_HEAR_WAIVED', 'CONTINU_DT', 'PCIS_REF_NBR',
       'SUBAREA_CD', 'CNAP', 'AZA_NM_EMPID', 'OLD_AZA_NM'],
      dtype='object')

,CASE_ID,AZA_ASGN_DT,AZA_NM,ZI_ASGN_DT,ZI_NM,HEAR_DT,HEAR_TM_TXT,HEAR_LOC_TXT,HEAR_NOTC_MEDIA_DT,HEAR_NOTC_PUBL_DT,ZI_RPT_DUE_DT,ZI_DRAFT_RPT_DT,ZI_RPT_CMPLT_DT,ZI_RPT_RCV_ZA_DT,ZA_ACTN_DT,ZA_ACTN_TXT,APEL_PRD_END_DT,ZA_SUPP_RPT_DUE_DT,BZA_CASE_NBR,ZA_APEL_SUBM_BZA_DT,ZA_ACTN_APEL_FLG,COND_ACTN_CLRNC_TXT,CASE_NBR_CHG_LOG_ID,CASE_FILE_RCV_DT,STF_ASGN_DT,ASGN_STF_NM,ASGN_STF_TEL_AREA_CD,ASGN_STF_TEL_NBR,RE_HEAR_NEEDED_FLG,HEAR_WAIVED_FLG,DT_HEAR_WAIVED,CONTINU_DT,PCIS_REF_NBR,SUBAREA_CD,CNAP,AZA_NM_EMPID,OLD_AZA_NM
0,161.0,1987-10-30,JON PERICA,1987-09-16,PARTAB RAMSINGHANI,1987-11-06,10 AM,VAN NUYS,NaT,NaT,1987-10-30,NaT,1987-10-30,1987-10-30,1988-03-01,None,1988-03-16,NaT,None,NaT,None,None,0.0,NaT,NaT,None,None,None,None,None,NaT,NaT,None,None,None,111,PERICA JON
1,164.0,NaT,JACK SEDWICK,NaT,None,NaT,None,None,NaT,NaT,NaT,NaT,NaT,NaT,1987-09-16,None,1987-10-01,NaT,None,NaT,None,None,0.0,NaT,NaT,None,None,None,None,None,NaT,NaT,None,None,None,JSEDWICK,SEDWICK JACK
2,166.0,NaT,JACK SEDWICK,NaT,None,NaT,None,None,NaT,NaT,NaT,NaT,NaT,NaT,1987-09-16,None,1987-09-30,NaT,None,NaT,None,None,0.0,NaT,NaT,None,None,None,None,None,NaT,NaT,None,None,None,JSEDWICK,SEDWICK JACK
3,168.0,NaT,JACK SEDWICK,NaT,None,NaT,None,None,NaT,NaT,NaT,NaT,NaT,NaT,1987-09-16,None,1987-10-01,NaT,None,NaT,None,None,0.0,NaT,NaT,None,None,None,None,None,NaT,NaT,None,None,None,JSEDWICK,SEDWICK JACK
4,170.0,NaT,None,1987-09-16,RICHARD HURD,1987-11-12,10:30 AM,"ROOM 250B, CH",NaT,NaT,1987-10-23,NaT,NaT,NaT,NaT,None,NaT,NaT,None,NaT,None,None,0.0,NaT,NaT,None,None,None,None,None,NaT,NaT,None,None,None,None,None

'trefDWELLING_UNIT_PROPTYPE'

Index(['TypeID', 'TypeName', 'Description', 'TypeLevel', 'ParentTypeID',
       'DisplayOrder', 'ActvFlg', 'CrtnDt', 'UpdatedTypeId'],
      dtype='object')

,TypeID,TypeName,Description,TypeLevel,ParentTypeID,DisplayOrder,ActvFlg,CrtnDt,UpdatedTypeId
0,1,Residential Dwelling Units,Residential Dwelling Units,1,0,1,True,NaT,None
1,2,Guest Rooms,Guest Rooms,1,0,2,True,NaT,None
2,3,Non Residential Sq Ft,Non Residential Square Footage,1,0,100,True,NaT,None
3,4,Market Rate,Market Rate,2,1,1,False,NaT,None
4,5,Affordable,Affordable,2,1,1,False,NaT,None

'trefDWELLING_UNIT_SPECIALGROUPS'

Index(['SpecialGroupID', 'SpecialGroupName', 'ActvFlg'], dtype='object')

   SpecialGroupID                                   SpecialGroupName  ActvFlg
0               2                                  Disabled Veterans     True
1               3                                           Veterans     True
2               4                                           Homeless     True
3               5  Special need and/or Persons with disabilities ...     True
4               6                         Transitional foster youths     True

'trefHOLD_STG'

Index(['HOLD_STG_ID', 'HOLD_STG_DESC', 'HOLD_STG_DESC_DSPLY', 'HOLD_STG_ORD'], dtype='object')

,HOLD_STG_ID,HOLD_STG_DESC,HOLD_STG_DESC_DSPLY,HOLD_STG_ORD
0,1.0,PRE-ACCEPTANCE,PRE-ACCEPTANCE,1.0
1,2.0,ACCEPTANCE TO HEARING,ACCEPTANCE TO HEARING,2.0
2,3.0,HEARING TO DETERMINATION,HEARING TO DETERMINATION,3.0