# Get into other tables from PCTS

In [1]:
import numpy as np
import pandas as pd
import geopandas as gpd
import intake

In [2]:
catalog = intake.open_catalog("../catalogs/*.yml")

In [3]:
list(catalog.pcts)

['tAPEL_CASE',
 'tAPLC',
 'tCASE',
 'tCOMMENT',
 'tCPC_CASE',
 'tDWELLING_UNITS',
 'tDWELLING_UNIT_SPECIALGROUPS',
 'tENV_CASE',
 'tHOLD_CASE',
 'tLA_PROP',
 'tLOC',
 'tPROP_CPIO',
 'tPROP_CUGU',
 'tPROP_GEO_INFO',
 'tPROP_SPECPLAN',
 'tZONING_CASE',
 'trefDWELLING_UNIT_PROPTYPE',
 'trefDWELLING_UNIT_SPECIALGROUPS',
 'trefHOLD_STG']

## tCASE
* CASE_ID is unique
* PCTS case # portion of CASE_NBR is not unique on year-PCTS case#

In [4]:
df = catalog.pcts.tCASE.read()
df.head()

,CASE_ID,CASE_NBR,OLD_CASE_NBR,OLD_REQ_TYP_CD,CASE_STTS_CD,APLC_ID,PLAN_OFC_ID,CASE_TYP_CD,CASE_FILE_RCV_DT,CASE_FILE_SENT_DT,...,PLAN_APPRV_TO_LIST,MAP_REQUESTED_DT,MAP_COMPLETED_DT,DWELLINGUNITREASONID,PROCESSING_UNIT_CODE,DISCRETNARY_FLG,ADM_ACTION_DT,ADM_ACTION_BY,LAST_DAYAPPEAL_DT,LASTDAYTOFILEENTITLEMENT
0,66.0,PC-1987-764-PC,PC-87-0764,PC,None,66.0,None,PC,NaT,NaT,...,None,NaT,NaT,0.0,None,None,NaT,None,NaT,NaT
1,67.0,PC-1987-761-PC,PC-87-0761,PC,None,67.0,None,PC,NaT,NaT,...,None,NaT,NaT,0.0,None,None,NaT,None,NaT,NaT
2,68.0,CPC-1987-640-ZC,CPC-87-640,ZC,None,68.0,None,CPC,NaT,NaT,...,None,NaT,NaT,0.0,None,None,NaT,None,NaT,NaT
3,70.0,PC-1987-758-PC,PC-87-0758,PC,None,70.0,None,PC,NaT,NaT,...,None,NaT,NaT,0.0,None,None,NaT,None,NaT,NaT
4,72.0,CPC-1987-630-BL,CPC-87-630,BL,None,72.0,None,CPC,NaT,NaT,...,None,NaT,NaT,0.0,None,None,NaT,None,NaT,NaT

In [5]:
df.CASE_ID.nunique()

211262

In [6]:
len(df)

211262

## tPROP_SPECPLAN
* specific plan info linked to PROP_ID

In [7]:
specific_plan = catalog.pcts.tPROP_SPECPLAN.read()

In [8]:
specific_plan.head()

      PROP_ID                               SPECPLAN  SPECIFICPLANID
0  59391255.0  Ventura / Cahuenga Boulevard Corridor            23.0
1  59391265.0  Ventura / Cahuenga Boulevard Corridor            23.0
2  59391268.0  Ventura / Cahuenga Boulevard Corridor            23.0
3  59036193.0                          Warner Center            26.0
4  58987755.0        South Los Angeles Alcohol Sales            14.0

In [11]:
len(specific_plan)

221243

In [13]:
specific_plan.PROP_ID.value_counts()

59547928.0    56
59210891.0     6
59159544.0     6
59159757.0     6
59210986.0     6
              ..
59110107.0     1
59199383.0     1
59018258.0     1
59110146.0     1
16.0           1
Name: PROP_ID, Length: 178854, dtype: int64

In [14]:
specific_plan[specific_plan.PROP_ID == 59547928]

,PROP_ID,SPECPLAN,SPECIFICPLANID
208772,59547928.0,Alameda District,NaN
208773,59547928.0,Avenue 57 Transit Oriented District,NaN
208774,59547928.0,Bunker Hill,NaN
208775,59547928.0,Central City West,NaN
208776,59547928.0,Century City North,NaN
208777,59547928.0,Century City South,NaN
208778,59547928.0,Coastal Bluffs,NaN
208779,59547928.0,Coliseum District,NaN
208780,59547928.0,Colorado Boulevard,NaN
208781,59547928.0,Convention and Event Center,NaN
208782,59547928.0,Cornfield / Arroyo Seco,NaN
208783,59547928.0,Crenshaw Corridor,NaN
208784,59547928.0,Del Rey Lagoon (Proposed),NaN
208785,59547928.0,Devonshire / Topanga Corridor,NaN
208786,59547928.0,Foothill Boulevard Corridor,NaN
208787,59547928.0,Girard Tract,NaN
208788,59547928.0,Glencoe / Maxella,NaN
208789,59547928.0,Granada Hills,NaN
208790,59547928.0,Hollywoodland,NaN
208791,59547928.0,Jordan Downs Urban Village,NaN
208792,59547928.0,LAX,NaN
208793,59547928.0,Los Angeles Airport / El Segundo Dunes,NaN
208794,59547928.0,Los Angeles Coastal Transportation Corridor,NaN
208795,59547928.0,Los Angeles Sports and Entertainment District,NaN
208796,59547928.0,Loyola Marymount University,NaN
208797,59547928.0,Mount Washington - Glassell Park,NaN
208798,59547928.0,Mulholland Scenic Parkway (Inner Corridor),NaN
208799,59547928.0,Mulholland Scenic Parkway (Outer Corridor),NaN
208800,59547928.0,North University Park,NaN
208801,59547928.0,North Westwood Village,NaN
208802,59547928.0,Oxford Triangle,NaN
208803,59547928.0,Pacific Palisades Commercial Village and Neigh...,NaN
208804,59547928.0,Paramount Pictures,NaN
208805,59547928.0,Park Mile,NaN
208806,59547928.0,Playa Vista (Area B),NaN
208807,59547928.0,Playa Vista (Area C),NaN
208808,59547928.0,Playa Vista (Area D),NaN
208809,59547928.0,Ponte Vista at San Pedro,NaN
208810,59547928.0,Porter Ranch Land Use / Transportation,NaN
208811,59547928.0,San Gabriel/Verdugo Mountains,NaN
208812,59547928.0,San Pedro,NaN
208813,59547928.0,San Vicente Scenic Corridor,NaN
208814,59547928.0,Sepulveda Corridor,NaN
208815,59547928.0,South Los Angeles Alcohol Sales,NaN
208816,59547928.0,University of Southern California University P...,NaN
208817,59547928.0,Valley Circle Boulevard - Plummer Street Sceni...,NaN
208818,59547928.0,Valley Village,NaN
208819,59547928.0,Venice Coastal Zone,NaN
208820,59547928.0,Ventura / Cahuenga Boulevard Corridor,NaN
208821,59547928.0,Vermont / Western Station Neighborhood Area Plan,NaN
208822,59547928.0,Warner Center,NaN
208823,59547928.0,West Los Angeles Transportation Improvement an...,NaN
208824,59547928.0,Westwood Community Design Review Board,NaN
208825,59547928.0,Westwood Community Plan Multiple Family Reside...,NaN
208826,59547928.0,Westwood Village,NaN
208827,59547928.0,Wilshire / Westwood Scenic Corridor,NaN

## tLA_PROP
* Looks like crosswalk between PROP_ID and ASSR_PRCL_NBR (APN)
* A m:1 merge with specific plan will tell us what specific plans apply to the parcels
* PROP_ID vs APN? 
* There are PROP_IDs with APNs that are Nones
* There are also APNs that are the same, but linked to different PROP_IDs.

In [9]:
la_prop = catalog.pcts.tLA_PROP.read()

In [10]:
la_prop.head()

,PROP_ID,PROP_TYP_CD,BOE_VLD_ADDR_FLG,PROP_CMN_NM,ASSR_PRCL_NBR,MULTI_PRCL_FLG,TRACT_NBR,BLCK_NBR,LOT_NBR,ARB_NBR,...,SYS_USER_ID,TIMESTAMP,PIN,APC_AREA_CD,CNC_CD,CRTN_ID,CRTN_DT,HPOZ,COMM_CNCL_CD,CRA_REDEV_PROJECTID
0,16.0,None,None,None,6058008014,None,TR 7906,None,90,None,...,TG_C5,1999-10-16 19:09:12,090A193 16,S,12.0,None,NaT,None,None,NaN
1,17.0,None,None,None,None,None,None,None,None,None,...,TG_C5,1999-10-16 19:09:12,None,None,NaN,None,NaT,None,None,NaN
2,18.0,None,None,None,None,None,None,None,None,None,...,TG_C5,1999-10-16 19:09:12,None,None,NaN,None,NaT,None,None,NaN
3,19.0,None,None,None,None,None,None,None,None,None,...,TG_C5,1999-10-16 19:09:12,None,None,NaN,None,NaT,None,None,NaN
4,20.0,None,None,None,None,None,None,None,None,None,...,PAV_M11,1999-11-16 14:20:49,None,None,NaN,None,NaT,None,None,NaN

In [15]:
la_prop[la_prop.PROP_ID == 59547928]

,PROP_ID,PROP_TYP_CD,BOE_VLD_ADDR_FLG,PROP_CMN_NM,ASSR_PRCL_NBR,MULTI_PRCL_FLG,TRACT_NBR,BLCK_NBR,LOT_NBR,ARB_NBR,...,SYS_USER_ID,TIMESTAMP,PIN,APC_AREA_CD,CNC_CD,CRTN_ID,CRTN_DT,HPOZ,COMM_CNCL_CD,CRA_REDEV_PROJECTID
604322,59547928.0,None,1,None,None,None,None,None,None,None,...,PCTS,2019-11-05 08:46:45,,CW,999.0,PCTS,2019-11-05 08:42:55,None,None,NaN

In [20]:
have_APN = la_prop[la_prop.ASSR_PRCL_NBR.notna()]
len(have_APN)

509706

In [18]:
len(la_prop)

605713

In [22]:
have_APN.ASSR_PRCL_NBR.nunique()

364273

In [23]:
have_APN.ASSR_PRCL_NBR.value_counts()

6046019930    305
4431015BRK    195
4129027902    191
5145018006    189
7440026903    171
             ...
4412013008      1
5869009301      1
2184037028      1
2559003017      1
5433010019      1
Name: ASSR_PRCL_NBR, Length: 364273, dtype: int64

In [25]:
multiple = ['6046019930', '7440026903']
have_APN[have_APN.ASSR_PRCL_NBR.isin(multiple)].sort_values(['ASSR_PRCL_NBR', 'PROP_ID'], ascending = [True, True])

,PROP_ID,PROP_TYP_CD,BOE_VLD_ADDR_FLG,PROP_CMN_NM,ASSR_PRCL_NBR,MULTI_PRCL_FLG,TRACT_NBR,BLCK_NBR,LOT_NBR,ARB_NBR,...,SYS_USER_ID,TIMESTAMP,PIN,APC_AREA_CD,CNC_CD,CRTN_ID,CRTN_DT,HPOZ,COMM_CNCL_CD,CRA_REDEV_PROJECTID
365774,59326706.0,None,1,None,6046019930,None,TR 16154,None,1,None,...,300229,2015-11-02 14:52:46,093A217 176,S,58.0,300229,2015-11-02 14:52:46,None,None,NaN
365775,59326707.0,None,1,None,6046019930,None,TR 16154,None,1,None,...,300229,2015-11-02 14:52:46,093A217 176,S,58.0,300229,2015-11-02 14:52:46,None,None,NaN
365776,59326708.0,None,1,None,6046019930,None,TR 16154,None,1,None,...,300229,2015-11-02 14:52:47,093A217 176,S,58.0,300229,2015-11-02 14:52:47,None,None,NaN
365622,59326709.0,None,1,None,6046019930,None,TR 16154,None,1,None,...,300229,2015-11-02 14:52:47,093A217 176,S,58.0,300229,2015-11-02 14:52:47,None,None,NaN
365777,59326710.0,None,1,None,6046019930,None,TR 16154,None,1,None,...,300229,2015-11-02 14:52:47,093A217 176,S,58.0,300229,2015-11-02 14:52:47,None,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317032,59258738.0,None,1,None,7440026903,None,TR 3921,6,11,None,...,PCTS,2014-02-28 08:34:42,018B201 181,H,3.0,PCTS,2014-02-28 08:34:42,None,None,NaN
315734,59258841.0,None,1,None,7440026903,None,TR 3921,3,7,None,...,PCTS,2014-02-28 08:34:44,018B201 248,H,3.0,PCTS,2014-02-28 08:34:44,None,None,NaN
316012,59258928.0,None,1,None,7440026903,None,TR 3921,3,2,None,...,PCTS,2014-02-28 08:34:44,018B201 301,H,3.0,PCTS,2014-02-28 08:34:44,None,None,NaN
313113,59260544.0,None,1,None,7440026903,None,RANCHO LOS PALOS VERDES,None,None,19,...,PCTS,2014-02-28 08:35:03,018B201 860,H,3.0,PCTS,2014-02-28 08:35:03,None,None,NaN
313115,59260546.0,None,1,None,7440026903,None,LANDS OF THE PACIFIC COAST STEAMSHIP CO.,5,13,None,...,PCTS,2014-02-28 08:35:03,018B201 870,H,3.0,PCTS,2014-02-28 08:35:03,None,None,NaN

## tPROP_GEO_INFO

In [26]:
geo_info = catalog.pcts.tPROP_GEO_INFO.read()

In [27]:
geo_info.head()

,PROP_GEO_INFO_ID,PROP_ID,CASE_ID,PROP_GEO_INFO_TYP,PROP_GEO_INFO_VAL,EFFECTIVE_DT,CNCL_DIST_NBR,TEMP_PIN,CRTN_DT,CRTN_ID,TIMESTAMP,SYS_USER_ID
0,350.0,34237.0,99538.0,CNCL_DIST_NBR,1,2002-08-20,1,135A209 39,2002-08-20,59527,2002-08-20,59527
1,351.0,34237.0,99539.0,CNCL_DIST_NBR,1,2000-12-04,1,135A209 39,2000-12-04,59527,2000-12-04,59527
2,352.0,34306.0,99666.0,CNCL_DIST_NBR,1,2001-05-14,1,130-5A201 171,2001-05-14,29592,2001-05-14,29592
3,353.0,34306.0,99667.0,CNCL_DIST_NBR,1,2000-12-12,1,130-5A201 171,2000-12-12,29592,2000-12-12,29592
4,354.0,34323.0,99722.0,CNCL_DIST_NBR,1,2001-05-18,1,135A213 210,2001-05-18,45375,2001-05-18,45375